## What is economics

Economics can be defined as means and ends to scarcity and can be manipulated by those in power. Thus the ends and means are not fixed.  

## Economics as science

Efficiency, both narrow and broad, are values and criteria for assessing outcomes in economics. Efficiencies deal with maximization or minimization of inputs or wastes respectively. Other key values in economics include fairness, freedom, trust and equality.

## Economics theories

- social: economy is embeded into the society; open information base.
- institutional: regulations by formal and informal; institutions. These regulations can be symmetric or asymmetric;closed information base.
- post-keynesian: concepts of lack of effective demand, uncertainty, and market power; open information base.
- neo-classical: idealized economic context where supply meets demand so that all resources are fully employed; closed information base.

* Closed information base resembles a cost-benefit base.


## Economics players

### State agencies


### Firms

Firms can be defined as hierarchical organization that produce and sell stuff. The objevtives of firms include constitution, market power, growth in market share, serving stakeholder interests.
Firms grow through investment and expansion to new markets. They stop growing when finance, labour, and transaction costs become bigger than profit. Therefore growth has an optimum beyond which they profit starts to decline. (Penrose Principle).


### Community actors


## Individuals and households

Multi-person households include both conflicts and cooperation. Households have multiple functions, e.g. act as unit for reproduction, have joint production through division of labour, operate under joint consumptions, and share income and risk pooling. 
There are also gender division of labour in households. This and other factors(e.g. resources, skills, opportunities, social support) could give rise to household bargaining concepts. These bargaining concepts can also act as threats and stereotypes as well as cooperations.

## Consumption

Consumption involves both _individual_ consumer demands (e.g. consumer goods, services, intermediate or durable consumer goods) as well as consumption by _states and communities_ (e.g. education, elderly care, sports). 
Consumer demands can affect budget constraints. 

Social economics of consumption are influenced by many factors such as advertisements, social norms, living standards, market power, consumer credits, and temptations.

# Markets

Monopoly is a market with only one seller. There are entry barriers in monopoly markets and the price setter is the monopolist who determines the price. Monopoly leads to high consumer prices.
The solutions to monopoly power are privatization (with sufficient competition) and benchmarking (ranking and rewards based on performance indicators). 

Oligopoly, on the other hand, is a market determined by a few large sellers. There are heterogenous goods that also have barriers to entry and have market power.

Monopsony is a market with only one buyer. The buyer is the price setter. This also includes entry barriers.
The solutions to the market power is promoting auctions for licenses to more buyers and state-buying agencies with democratic control.

Monopolistic competition includes large number of buyers and sellers and low entry barriers. These include heterogenous goods. For this competition, location and advertisement matters. In these markets, the winner takes all.

Perfect competition is the ideal market with many suppliers and many buyers which leads to low entry barriers and exchanged goods. This market has a long-run efficiency in which cost reduction increases profits. The increased profit attract new entrants which then increase compeition which additionally lower the prices to attract customers.

## Market failures
There are various ways for markets to fail. Monopsony and monopolistic competition markets are more stable. The perfect competition market is more volatile in an imprefect world. Market imprefections can be due to skill differences, luck, accumulation by capital owners through mergers and take-overs.


### Types of data suitable for econometric analyses
1. cross sectional data
2. time series data
3. panel data

